# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Daniela Patrício
tagline:          'Data Analyst'
description:      'Data Analyst'
url:              http://danielapatricio.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           http://danielapatricio.github.io
